name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Vet
        run: go vet -v -unreachable=false ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
